services:
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
        
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - /data/db
        
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
        
  auction-svc:
    image: robertgee/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # For logging during development
      - ASPNETCORE_URLS=http://+:80 # Internal URL
      - RabbitMq__Host=rabbitmq # Specifying container
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
      - IdentityServiceUrl=http://identity-svc
    ports:
      - "7001:80" # Same port for all services due to unique IP
    depends_on:
      - rabbitmq
      - postgres
  
  search-svc:
    image: robertgee/search-svc
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development # For logging during development
      - ASPNETCORE_URLS=http://+:80 # Internal URL
      - RabbitMq__Host=rabbitmq # Specifying container
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    ports:
      - "7002:80" # Same port for all services due to unique IP
    depends_on:
      - mongodb
      - rabbitmq
      
  identity-svc:
    image: robertgee/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker # For logging during development
      - ASPNETCORE_URLS=http://+:80 # Internal URL
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - "5001:80" # Same port for all services due to unique IP
    depends_on:
      - postgres
      
  gateway-svc:
    image: robertgee/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker # For logging during development
      - ASPNETCORE_URLS=http://+:80 # Internal URL
    ports:
      - "6001:80" # Same port for all services due to unique IP
        
volumes:
  pgdata:
  mongodata: